TELEGRAM_CHANNELS = [
    'https://t.me/imtproxy_ir',
    'https://t.me/NetAccount',
    'https://t.me/proxyy',
    'https://t.me/Myporoxy',
    'https://t.me/iRoProxy',
    'https://t.me/darkproxy',
    'https://t.me/iMTProto',
    'https://t.me/proxymtprotoir',
    'https://t.me/MtProxy_blue',
    'https://t.me/ROCKETTUNNEL',
    'https://t.me/VPN_SOLVE',
    'https://t.me/Not_Proxyy',
    'https://t.me/proxyyj',
    'https://t.me/mtp_proxyyyy',
    'https://t.me/ProxyMTProto',
    'https://t.me/P500Y',
    'https://t.me/jackalproxy',
    'https://t.me/Chrome_Proxy',
    'https://t.me/mnmn_32',
    
] 